name: Dominion CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
