name: Dominion CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
