name: Dominion CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Did we break README example?
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -- --ban-cards Witch --include-cards YoungWitch --include-expansions Base2 Renaissance --project-count 2 --hists --pretty
      
